//Anthony Nunn
//email: avnunn@gmail.com
//site: anthonynunn.org

//Euler 2
//Date: 7/12/2010
//http://projecteuler.net/index.php?section=problems&id=2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//Find the sum of all the even-valued terms in the sequence which do not exceed four million.

#include <stdio.h>

#define FOUR_MILLION		4000000
#define FIRST_FSEQUENCE		1
#define SECOND_FSEQUENCE	2

int main(){
	// Set the first two values for the fibinacci sequence
	int previous	= FIRST_FSEQUENCE;
	int current		= SECOND_FSEQUENCE;

	// Going to need a temp holding value throught program
	int backUp	= 0;

	// Hold the sum
	int sum		= 0;

	// Continue the pattern unless number exceeds four million
	while (current <= FOUR_MILLION){
		printf("%i\n", current);
		sum += current;

		//Move forward the sequence 3 times
		backUp = current;
		current += previous;
		previous = backUp;

		backUp = current;
		current += previous;
		previous = backUp;

		backUp = current;
		current += previous;
		previous = backUp;
	}
	
	printf("\n\nSum of even numbers of the Fibonacci sequence below four million is: %i.\n", sum);

	return 0;
}